package com.sst.generico10.model.appconfiguration;

public enum AppConfigurationKey {
	ADMIN_EMAIL, ADMIN_EMAIL_PASSWORD, ADMIN_EMAIL_SMTP_PORT, ADMIN_EMAIL_SMTP_HOST, ADMIN_EMAIL_SMTP_TLS, ADMIN_EMAIL_SMTP_USER, ADMIN_EMAIL_SMTP_AUTH, USER_PASSWORD_RESET_TIME, APP_URL;

}
